name: inverse-game-discount-factor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - matplotlib
  - tqdm
  - jax>=0.4.6
  - mediapy
  - pip:
    - git+https://github.com/waymo-research/waymax.git@main#egg=waymo-waymax 